# Website details
name: "ERKAN CEYLAN"
description: "Programmer From Somewhere On Earth"
email: "erkanceylan4@gmail.com"
author: "erkanceylan"
lang: "tr"
locale: ""

# Jekyll
paginate: 10
highlighter: ""
markdown: kramdown
gems: [jekyll-paginate]
timezone: Europe/Istanbul
paginateLabel: page
paginate_path: "page/:num"
permalink: /:categories/:year/:month/:day/:title
baseurl: http://erkanceylan.com
aboutUrl: http://erkanceylan.com/about
projectsUrl: http://erkanceylan.com/projects

# Includes
addthisId: ""
disqusUsername: "erkanceylan4"
googleAnalyticsId: "UA-63036486-2"

# Search engine verifications
bing: ""
yandex: ""
google: ""

#Sitemap
sitemap:
    file: "/sitemap.xml"
    exclude:
        - "/404.html"
    include_posts:
        - "/index.html"
    change_frequency_name: "daily"
    priority_name: "1.00"
