# Site
name: "Erkan Ceylan"
description: "Web ve Android Yazılım Geliştirici."
meta_description: "erkan ceylan, web, yazılım geliştirici, blog, kişisel web sitesi"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: /
google_analytics: 'UA-63036486-2'
disqus: 'erkanceylan4'
mailchimp-list: ''
mailchimp-list: '"https://erkanceylan.us18.list-manage.com/subscribe/post?u=ead13e95241587ea997e07942&amp;id=3521e48a0b'

# Authors
authors:
  erkan:
    name: Erkan
    display_name: Erkan
    gravatar: 1f256f0470eab78af49102de4d40f59c.
    email: contact@erkanceylan.com
    web: https://erkanceylan.com
    twitter: https://twitter.com/erkan4ceylan
    description: "Sitenin sahibi."
  
# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown
highlighter: rouge
